# Generated by Django 5.2.11 on 2026-02-28 12:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusSabab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('pul_miqdori', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ball_miqdori', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bonus sababi',
                'verbose_name_plural': 'Bonus sabablari',
            },
        ),
        migrations.CreateModel(
            name='JarimaSabab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('pul_miqdori', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ball_miqdori', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Jarima sababi',
                'verbose_name_plural': 'Jarima sabablari',
            },
        ),
        migrations.CreateModel(
            name='Xodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familya', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('bonus_ball', models.IntegerField(default=0)),
                ('bonus_pul', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('jarima_ball', models.IntegerField(default=0)),
                ('jarima_pul', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reyting_ball', models.IntegerField(default=0)),
                ('reyting_pul', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xodim', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ['-reyting_ball'],
            },
        ),
        migrations.CreateModel(
            name='JarimaRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pul_miqdori', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ball_miqdori', models.IntegerField()),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('izoh', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sabab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.jarimasabab')),
                ('xodim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jarima_recordlari', to='main.xodim')),
            ],
            options={
                'verbose_name': 'Jarima yozuvi',
                'verbose_name_plural': 'Jarima yozuvlari',
                'ordering': ['-sana'],
            },
        ),
        migrations.CreateModel(
            name='BonusRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pul_miqdori', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ball_miqdori', models.IntegerField()),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('izoh', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sabab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.bonussabab')),
                ('xodim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_recordlari', to='main.xodim')),
            ],
            options={
                'verbose_name': 'Bonus yozuvi',
                'verbose_name_plural': 'Bonus yozuvlari',
                'ordering': ['-sana'],
            },
        ),
        migrations.CreateModel(
            name='Reyting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('davr', models.CharField(choices=[('kunlik', 'Kunlik'), ('haftalik', 'Haftalik'), ('oylik', 'Oylik'), ('yillik', 'Yillik')], max_length=20)),
                ('bonus_ball', models.IntegerField(default=0)),
                ('bonus_pul', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('jarima_ball', models.IntegerField(default=0)),
                ('jarima_pul', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reyting_ball', models.IntegerField(default=0)),
                ('reyting_pul', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sana', models.DateField(default=django.utils.timezone.now)),
                ('xodim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reytinglari', to='main.xodim')),
            ],
            options={
                'ordering': ['-reyting_ball'],
                'unique_together': {('xodim', 'davr', 'sana')},
            },
        ),
    ]
