# Generated by Django 5.2.11 on 2026-03-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodim',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='xodim_rasmlari/'),
        ),
    ]
