# Generated by Django 5.2.12 on 2026-03-04 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_xodim_rasm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OzgartirishTarixi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabab', models.TextField()),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('eski_bonus_ball', models.IntegerField(default=0)),
                ('eski_bonus_pul', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('eski_jarima_ball', models.IntegerField(default=0)),
                ('eski_jarima_pul', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('yangi_bonus_ball', models.IntegerField(default=0)),
                ('yangi_bonus_pul', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('yangi_jarima_ball', models.IntegerField(default=0)),
                ('yangi_jarima_pul', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('xodim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ozgartirish_tarixlari', to='main.xodim')),
            ],
            options={
                'verbose_name': "O'zgartirish tarixi",
                'verbose_name_plural': "O'zgartirish tarixlari",
                'ordering': ['-sana'],
            },
        ),
    ]
