# Generated by Django 5.2.12 on 2026-03-05 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ozgartirishtarixi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonusrecord',
            options={},
        ),
        migrations.AlterModelOptions(
            name='jarimarecord',
            options={},
        ),
        migrations.AlterField(
            model_name='bonusrecord',
            name='ball_miqdori',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bonusrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bonusrecord',
            name='izoh',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bonusrecord',
            name='pul_miqdori',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bonusrecord',
            name='sabab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.bonussabab'),
        ),
        migrations.AlterField(
            model_name='jarimarecord',
            name='ball_miqdori',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jarimarecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jarimarecord',
            name='izoh',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jarimarecord',
            name='pul_miqdori',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='jarimarecord',
            name='sabab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.jarimasabab'),
        ),
    ]
