# Generated by Django 5.2.12 on 2026-03-05 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_bonusrecord_options_alter_jarimarecord_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonusrecord',
            options={'ordering': ['-sana'], 'verbose_name': 'Bonus yozuvi', 'verbose_name_plural': 'Bonus yozuvlari'},
        ),
        migrations.AlterModelOptions(
            name='jarimarecord',
            options={'ordering': ['-sana'], 'verbose_name': 'Jarima yozuvi', 'verbose_name_plural': 'Jarima yozuvlari'},
        ),
    ]
