# Generated by Django 5.2.12 on 2026-03-10 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_bonusrecord_options_alter_jarimarecord_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BallOchirishTarixi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('bonus', 'Bonus'), ('jarima', 'Jarima')], max_length=10)),
                ('record_id', models.PositiveIntegerField()),
                ('ball_miqdori', models.IntegerField()),
                ('pul_miqdori', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sabab', models.CharField(max_length=255)),
                ('eski_izoh', models.TextField(blank=True)),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ochirilgan_ballar', to=settings.AUTH_USER_MODEL)),
                ('xodim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ball_ochirish_tarixlari', to='main.xodim')),
            ],
            options={
                'verbose_name': "Ball o'chirish tarixi",
                'verbose_name_plural': "Ball o'chirish tarixlari",
                'ordering': ['-sana'],
            },
        ),
    ]
