# Generated by Django 5.2.12 on 2026-03-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_ballochirishtarixi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BallOchirishTarixi',
        ),
    ]
