# Generated by Django 5.2.12 on 2026-04-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_ballochirishtarixi'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodim',
            name='reyting_ball_adjustment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='xodim',
            name='reyting_pul_adjustment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
