# Generated by Django 4.2 on 2026-04-20 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_xodim_reyting_ball_adjustment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YechishRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(choices=[('bonus', 'Bonusdan yechildi'), ('jarima', 'Jarimadan yechildi')], max_length=10)),
                ('ball_miqdori', models.IntegerField(default=0)),
                ('pul_miqdori', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sabab', models.TextField()),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('xodim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yechish_recordlari', to='main.xodim')),
            ],
            options={
                'verbose_name': 'Yechish',
                'verbose_name_plural': 'Yechishlar',
                'ordering': ['-sana'],
            },
        ),
    ]
