# Generated by Django 4.2.20 on 2026-05-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_yechishrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YechishRecord',
        ),
    ]
