# Generated by Django 4.2 on 2026-05-04 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_delete_yechishrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodim',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='xodim',
            name='lavozim',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='xodim',
            name='oxirgi_pul_reset',
            field=models.DateField(blank=True, help_text='Oxirgi marta pul reset qilingan sana', null=True),
        ),
        migrations.AlterField(
            model_name='xodim',
            name='bonus_ball',
            field=models.IntegerField(default=0, help_text="Jami bonus ball (hech qachon reset bo'lmaydi)"),
        ),
        migrations.AlterField(
            model_name='xodim',
            name='bonus_pul',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Joriy bonus pul (oylik reset qilinadi)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='xodim',
            name='jarima_ball',
            field=models.IntegerField(default=0, help_text="Jami jarima ball (hech qachon reset bo'lmaydi)"),
        ),
        migrations.AlterField(
            model_name='xodim',
            name='jarima_pul',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Joriy jarima pul (oylik reset qilinadi)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='xodim',
            name='reyting_ball',
            field=models.IntegerField(default=0, help_text='Ball reyting (bonus - jarima)'),
        ),
        migrations.AlterField(
            model_name='xodim',
            name='reyting_pul',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pul reyting (bonus - jarima)', max_digits=12),
        ),
        migrations.CreateModel(
            name='OylikPulReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eski_bonus_pul', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('eski_jarima_pul', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('eski_reyting_pul', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('yil', models.IntegerField()),
                ('oy', models.IntegerField()),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('izoh', models.TextField(blank=True, default='')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('xodim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oylik_resetlar', to='main.xodim')),
            ],
            options={
                'verbose_name': 'Oylik pul reset',
                'verbose_name_plural': 'Oylik pul resetlar',
                'ordering': ['-sana'],
                'unique_together': {('xodim', 'yil', 'oy')},
            },
        ),
    ]
