# Generated by Django 4.2 on 2026-05-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_xodim_active_xodim_lavozim_xodim_oxirgi_pul_reset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xodim',
            name='active',
        ),
        migrations.RemoveField(
            model_name='xodim',
            name='lavozim',
        ),
        migrations.RemoveField(
            model_name='xodim',
            name='oxirgi_pul_reset',
        ),
        migrations.AlterField(
            model_name='xodim',
            name='bonus_ball',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='xodim',
            name='bonus_pul',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='xodim',
            name='jarima_ball',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='xodim',
            name='jarima_pul',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='xodim',
            name='reyting_ball',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='xodim',
            name='reyting_pul',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.DeleteModel(
            name='OylikPulReset',
        ),
    ]
