# Generated by Django 4.2 on 2026-05-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_xodim_active_remove_xodim_lavozim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodim',
            name='bonus_pul_yechilgan',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Bonus pulidan yechilgan summa', max_digits=12),
        ),
        migrations.AddField(
            model_name='xodim',
            name='jarima_pul_yechilgan',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Jarima pulidan yechilgan summa', max_digits=12),
        ),
    ]
