# Generated by Django 4.2 on 2026-05-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_xodim_bonus_pul_yechilgan_xodim_jarima_pul_yechilgan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xodim',
            name='reyting_ball_adjustment',
        ),
        migrations.RemoveField(
            model_name='xodim',
            name='reyting_pul_adjustment',
        ),
        migrations.AddField(
            model_name='ozgartirishtarixi',
            name='eski_bonus_yechilgan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ozgartirishtarixi',
            name='eski_jarima_yechilgan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ozgartirishtarixi',
            name='yangi_bonus_yechilgan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ozgartirishtarixi',
            name='yangi_jarima_yechilgan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='xodim',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='xodim',
            name='lavozim',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='xodim',
            name='bonus_pul_yechilgan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='xodim',
            name='jarima_pul_yechilgan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
