# Generated by Django 4.2 on 2026-05-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_xodim_reyting_ball_adjustment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ozgartirishtarixi',
            old_name='eski_jarima_yechilgan',
            new_name='eski_bonus_pul_yechilgan',
        ),
        migrations.RenameField(
            model_name='ozgartirishtarixi',
            old_name='eski_bonus_yechilgan',
            new_name='eski_jarima_pul_yechilgan',
        ),
        migrations.RenameField(
            model_name='ozgartirishtarixi',
            old_name='yangi_bonus_yechilgan',
            new_name='yangi_bonus_pul_yechilgan',
        ),
        migrations.RenameField(
            model_name='ozgartirishtarixi',
            old_name='yangi_jarima_yechilgan',
            new_name='yangi_jarima_pul_yechilgan',
        ),
        migrations.AddField(
            model_name='ozgartirishtarixi',
            name='eski_bonus_ball_yechilgan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ozgartirishtarixi',
            name='eski_jarima_ball_yechilgan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ozgartirishtarixi',
            name='yangi_bonus_ball_yechilgan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ozgartirishtarixi',
            name='yangi_jarima_ball_yechilgan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='xodim',
            name='bonus_ball_yechilgan',
            field=models.IntegerField(default=0, help_text='Yechilgan bonus ball'),
        ),
        migrations.AddField(
            model_name='xodim',
            name='jarima_ball_yechilgan',
            field=models.IntegerField(default=0, help_text='Yechilgan jarima ball'),
        ),
        migrations.AlterField(
            model_name='xodim',
            name='bonus_ball',
            field=models.IntegerField(default=0, help_text='Umumiy bonus ball'),
        ),
        migrations.AlterField(
            model_name='xodim',
            name='bonus_pul',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Umumiy bonus pul', max_digits=12),
        ),
        migrations.AlterField(
            model_name='xodim',
            name='bonus_pul_yechilgan',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Yechilgan bonus pul', max_digits=12),
        ),
        migrations.AlterField(
            model_name='xodim',
            name='jarima_ball',
            field=models.IntegerField(default=0, help_text='Umumiy jarima ball'),
        ),
        migrations.AlterField(
            model_name='xodim',
            name='jarima_pul',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Umumiy jarima pul', max_digits=12),
        ),
        migrations.AlterField(
            model_name='xodim',
            name='jarima_pul_yechilgan',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Yechilgan jarima pul', max_digits=12),
        ),
        migrations.AlterField(
            model_name='xodim',
            name='reyting_ball',
            field=models.IntegerField(default=0, help_text='Sof reyting ball (bonus - jarima)'),
        ),
        migrations.AlterField(
            model_name='xodim',
            name='reyting_pul',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sof reyting pul', max_digits=12),
        ),
    ]
