# Generated by Django 4.2 on 2026-05-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_product_productorder_pointtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodim',
            name='xarid_ball',
            field=models.IntegerField(default=0, help_text='Shopda sarflangan ball'),
        ),
    ]
