# Generated by Django 4.2 on 2026-07-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodim',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Arxivlangan xodim'),
        ),
    ]
