# Generated by Django 5.1 on 2026-07-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_xodim_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_bot_token', models.CharField(blank=True, default='', help_text='BotFather dan olingan token', max_length=255, verbose_name='Telegram Bot Token')),
                ('telegram_chat_id', models.CharField(blank=True, default='', help_text='Xabar yuboriladigan guruh/yakka chat ID', max_length=100, verbose_name='Telegram Chat ID')),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
    ]
