# Generated by Django 5.1 on 2026-07-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_thread_id',
            field=models.CharField(blank=True, default='', help_text="Forum guruh uchun topic ID (bo'sh qolsa umumiy chatga yuboriladi)", max_length=100, verbose_name='Telegram Thread ID'),
        ),
    ]
