# Generated by Django 4.2 on 2026-08-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_fix_sequences'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='restore_yechilgan_applied',
            field=models.BooleanField(default=False, help_text="Deploy paytida yo'qolgan yechishlar bir marta qayta tiklangan (ikki marta qo'shilmasligi uchun)", verbose_name='Restore bajarildi'),
        ),
    ]
