# Generated by Django 5.0.14 on 2026-09-02 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_sitesettings_restore_yechilgan_applied'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Kalit (unik)')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('text', models.TextField(verbose_name='Matn')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Admin e'loni",
                'verbose_name_plural': "Admin e'lonlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminAnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(verbose_name='Admin ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='main.adminannouncement')),
            ],
            options={
                'verbose_name': "O'qilgan e'lon",
                'verbose_name_plural': "O'qilgan e'lonlar",
                'unique_together': {('user_id', 'announcement')},
            },
        ),
    ]
